###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwordrules.operator.ibm.com
  labels:
    app: {{ .Values.platformApi.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.platformApi.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name:  {{ .Release.Name }}
    helm.sh/chart: {{ .Release.Name }}
spec:
  group: operator.ibm.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: PasswordRule
    listKind: PasswordRuleList
    plural: passwordrules
    singular: passwordrule
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            description:
              type: string
            regex:
              type: string

---
apiVersion: operator.ibm.com/v1
kind: PasswordRule
metadata:
  name: rule-default
spec:
  description: "default password rule"
  regex: "^([a-zA-Z0-9\\-](32,))$"