apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: platform-api-ss-issuer
  namespace: {{ .Values.platformApi.namespace }}
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: platform-api-ca-certificate
  namespace: {{ .Values.platformApi.namespace }}
spec:
  issuerRef:
    name: platform-api-ss-issuer
    kind: Issuer
  secretName: platform-api-cluster-ca-cert
  commonName: ca-certificate
  isCA: true
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: cs-ca-clusterissuer
spec:
  ca:
    secretName: platform-api-cluster-ca-cert