---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api-sa
  labels:
    name: platform-api-sa
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    helm.sh/chart: platform-api:3.6.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-api
  labels:
    name: platform-api
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    helm.sh/chart: platform-api:3.6.0
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-api-privileged
  labels:
    name: platform-api-privileged
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    helm.sh/chart: platform-api:3.6.0
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - serviceaccounts 
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies 
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-api
  labels:
    name: platform-api
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    helm.sh/chart: platform-api:3.6.0
subjects:
- kind: ServiceAccount
  name: platform-api-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-api-privileged
  labels:
    name: platform-api-privileged
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    helm.sh/chart: platform-api:3.6.0
subjects:
- kind: ServiceAccount
  name: platform-api-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-api-privileged
