apiVersion: v1
kind: ConfigMap
metadata:
  name: ibmcloud-cluster-info
  namespace: kube-public
data:
  cluster_address: icp-console.apps.{{ .Values.platformApi.config.clusterExternalAddress }}
  cluster_ca_domain: {{ .Values.platformApi.config.clusterCAdomain }}
  cluster_endpoint: https://icp-management-ingress.{{ .Values.platformApi.namespace }}.svc:443
  cluster_kube_apiserver_host: api.{{ .Values.platformApi.config.clusterExternalAddress }}
  cluster_kube_apiserver_port: "6443"
  cluster_name: {{ .Values.platformApi.config.clusterName }}
  cluster_router_http_port: "8080"
  cluster_router_https_port: "443"
  edition: Enterprise Edition
  openshift_router_base_domain: apps.{{ .Values.platformApi.config.clusterExternalAddress }}
  proxy_address: icp-proxy.apps.{{ .Values.platformApi.config.clusterExternalAddress }}
  proxy_ingress_http_port: "80"
  proxy_ingress_https_port: "443"
  version: 3.3.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibmcloud-cluster-info
  namespace: kube-public
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  resourceNames:
  - ibmcloud-cluster-info
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibmcloud-cluster-info
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: "system:authenticated"
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: "system:unauthenticated"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibmcloud-cluster-info