apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
