apiVersion: v1
kind: ServiceAccount
metadata:
  name: platformapis.operator.ibm.com
  labels:
    name: platformapis.operator.ibm.com
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
