appVersion: 3.2.1
description: ICP Platform API Service
keywords:
- kubernetes
- IBM Cloud Private
- API
- IcpClusterResource
- s390x
- ppc64le
- amd64
- ICP
- Development
- Commercial
kubeVersion: '>=1.11.0'
maintainers:
- email: icpapi@us.ibm.com
  name: IBM Cloud Private
name: platform-api
tillerVersion: '>=2.9.1'
version: 3.4.0
